# create deployment file for nginx 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: testapp
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: testapp
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: rules-service
            mountPath: /usr/share/nginx/html/
      volumes:
      - name: rules-service
        configMap:
          name: rule-configmap

---
# create a service for the deployment 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: testapp
  namespace: default
spec:
  selector:
    app: testapp
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30829   # should be the same with the ingressgateway forwarding nodeport
