apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mod-example
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  url: oci://registry.fi.intel.com/staging/modsecurity_wasm:latest
  imagePullPolicy: Always
  pluginConfig:
    "rules_service": rule-service
    "duration_time": "30"
