apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: mod-example
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  url: oci://registry.fi.intel.com/wujiayu/envoy-modsecurity-wasm-dynamic-plugin:latest
  imagePullPolicy: Always
  pluginConfig:
    "pod_name": "istio-ingressgateway"
    "name_space": "istio-system"
    "rules_service": ruleserver-controller-manager-ruleserver-service
    "duration_time": "30"
