name: Build Rule server

on:[]

jobs:
  build-ruleserver:
    runs-on: ubuntu-20.04
    steps:
      # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: "1.17"

      - name: Check go.mods
        uses: evantorrie/mott-the-tidier@v1-beta
        with:
          gomods: |
            **/go.mod

      - name: download dependencies
        run: go get ./...

      - name: Lint files
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29

      - name: Build server
        run: CGO_ENABLED=0 go build main.go

      - name: Run tests
        run: CGO_ENABLED=1 go test -v ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./ruleserver
          push: false
